# Generated by Django 4.2.2 on 2023-06-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='information',
            field=models.URLField(blank=True, null=True),
        ),
    ]
